apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      imagePullSecrets:
        - name: acr-auth
      containers:
        - name: checkoutservice
          image: ecommerceusecase.azurecr.io/checkoutservice-nonprod:latest
          ports:
            - containerPort: 9555
          env:
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingservice.nonprod.svc.cluster.local:4051"
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: nonprod
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
    - name: http
      port: 5050
      targetPort: 5050
