apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
       - name: server
         image: ecommerceusecase.azurecr.io/frontend-nonprod:latest
         ports:
          - containerPort: 8080
      imagePullSecrets:
       - name: imagepull
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: nonprod
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
    

