apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: server
          image: ecommerceusecase.azurecr.io/paymentservice:v1
          ports:
            - containerPort: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: nonprod
spec:
  type: ClusterIP
  selector:
    app: paymentservice
  ports:
  - name: http
    port: 50051
    targetPort: 50051
