apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  namespace: nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      imagePullSecrets:
        - name: acr-auth
      containers:
        - name: redis
          image: "redis:alpine"
          ports:
            - containerPort: 6379
      volumes:
        - name: redis-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  namespace: nonprod
spec:
  type: ClusterIP
  selector:
    app: redis-cart
  ports:
  - name: tcp-redis
    port: 6379
    targetPort: 6379
