apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
        - name: shippingservice
          image: ecommerceusecase.azurecr.io/shippingservice:v1
          ports:
            - containerPort: 4051

---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: nonprod
spec:
  type: ClusterIP
  selector:
    app: shippingservice
  ports:
  - name: http
    port: 4051
    targetPort: 4051
