name: Build and Deploy to AKS - ShippingService

on:
  push:
    branches: ["Dev"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker images
        run: |
          cd src/shippingservice
          docker build -t ${{ secrets.ACR_REGISTRY }}/shippingservice-nonprod:latest .
          docker push ${{ secrets.ACR_REGISTRY }}/shippingservice-nonprod:latest

      - name: Deploy to AKS
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Apply Kubernetes manifests
        run: |
          cd kubernetes/Manifest
          kubectl apply -f shippingservice.yaml
